### ISSUE TITLE
Not compatible with matplotlib version >= 3.3.0

### ISSUE THREAD

**Issue by tonivss** [martinbarry59/neurodynex3#1]
Since matplotlib replaced the method `set_clim()` by `ScalarMappable.set_clim` (see [https://github.com/matplotlib/matplotlib/blob/a8831d57207db5e9bf681e30810ce0ea146f4a31/doc/api/prev_api_changes/api_changes_3.3.0/removals.rst](url)) the code will not execute.
Using `neurodynex3.hopfield_network.plot_tools.plot_overlap_matrix()` requires matplotlib <= 3.2.2

**Comment by martinbarry59** [comment]
Hey thank you for the feedback. It is solved now. FYI we are going to delete this github folder and move everything here:

https://github.com/EPFL-LCN/neuronaldynamics-exercises

Best.
